# Generated by Django 3.2.5 on 2021-07-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customfee', '0002_alter_customfeeinfo_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFeeHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_fee_id', models.IntegerField()),
                ('client_id', models.CharField(max_length=6)),
                ('taker_fee', models.DecimalField(decimal_places=8, max_digits=8)),
                ('maker_fee', models.DecimalField(decimal_places=8, max_digits=8)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('staff_email', models.EmailField(max_length=254)),
                ('register_type', models.CharField(max_length=10)),
                ('observation', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomFeeInfo',
        ),
    ]
